### ISSUE TITLE
Выложить новую тему

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#1]
Новая тема пока доступна по флагу `?lwtheme=test`. Дописывайте флаг к ссылкам-примерам, чтобы было понятно, о чём речь.

* [x] #17 перекрасить верхнее меню
* [x] #18 поправить отступы
* [x] #19 поправить слишком жирные подчёркивания ссылок
* [ ] #20 поправить стили secondary tabs ([пример](http://lesswrong.ru/node/225/revisions/1597/view))
* [ ] #21 поправить отступы для таблиц ([пример](http://lesswrong.ru/changelog))
* [x] разобраться с меню
* [x] ревизия шрифтов
* [x] увеличить вертикальное расстояние между ссылками на переводы
* [x] отдельный цвет для visited-ссылок

**Comment by berekuk** [comment]
## План про скрещивание друпала и медиавики
tl;dr: оставить переводы в друпале, все материалы писать на вики, будущие разделы делать на друпале или вики в зависимости от того, нужны ли там структурированные данные и сложная бизнес-логика.

### Подробности
1) Сделать на lesswrong.ru (в рамках новой темы) шапку:
`[ Переводы | Вики | Встречи | Форум | Чат ]`
По дизайну - не совсем как на http://lesswrong.ru/?lwtheme=test, хочу её ещё ужать в одну строку - логотип и ссылки, высотой 50-60px.

2) На главной lesswrong.ru сделать нормальный лендинг, без той стены текста, как сейчас.

3) Шапку по возможности прикрутить к существующим вики и форуму. “Чат” - ведёт на lesswrong.ru/slack, пока видимо тоже на друпале (со временем туда же прикрутить сервисы с git.dektyarev.name).

4) “Встречи” - в первом релизе шапки этого раздела не будет, но в будущем будет, пока на друпале или на чём-то ещё, но не на медиавики. Почему: потому что это как раз кейс для структурированных данных с бизнес-логикой.

5) “Форум” - ну, пока нет ресурсов для запуска нового форума, но я всё ещё считаю, что в будущем он понадобится (смена движка, в смысле). Когда понадобится, решим, как именно.

6) Самое главное, “Вики” - предлагаю туда переносить всё, кроме переводов. В том числе всё из http://lesswrong.ru/content, кроме видимо /slack. Точно туда - "Список литературы” и “Материалы и ресурсы”. И всё толковое с хакпада.

7) “Переводы” хочу оставить на друпале по нескольким причинам:
- Главное: слишком муторно будет править форматирование под медиавики.
- И иерархическую структуру переносить тоже долго.
- Хорошо, что они в одном кластере /w/ и что по урлам можно отличить, где что.
- Вёрстка “переводов” соптимизирована (или будет на новой теме соптимизирована) под чтение, а не под быстрое просматривание: крупный шрифт, относительно короткие строки. На вики шрифт мелкий и строки очень длинные, можно считать это багом, но можно и фичей: больше влезает на экран, для энциклопедии это важнее читаемости текста.
